filter:
    excluded_paths: [tests/*]
checks:
    php: true
tools:
    php_mess_detector: true
    php_pdepend: true
    php_code_coverage: false
    external_code_coverage: false
    php_analyzer: true
    php_code_sniffer:
        config:
            standard: PSR4
        filter:
            paths: ['src']
    sensiolabs_security_checker: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, test]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
